version: '3.8'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    volumes: 
      - ./src:/var/www/html
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
    volumes: 
      - db_data:/var/lib/mysql

volumes:
  db_data: